### ISSUE TITLE
Try to rebuild Filament Database

### ISSUE THREAD

**Issue by digitaljunk** [OllisGit/OctoPrint-FilamentManager#1]
I lost an SD card due power loss and needed to rebuild my octopi installation. I have some backups taken the other day (oprint, .octoprint Directories) but I have no simple export of the FilamentManager Filament database. I try to find the database in my backups. Can someone please point me to it? Or am I lost?

**Comment by NotExpectedYet** [comment]
> 
> 
> I lost an SD card due power loss and needed to rebuild my octopi installation. I have some backups taken the other day (oprint, .octoprint Directories) but I have no simple export of the FilamentManager Filament database. I try to find the database in my backups. Can someone please point me to it? Or am I lost?

It's in your .octoprint folder somewhere I believe. Do you have a plugin data folder? I forget what it looks like.

**Comment by OllisGit** [comment]
Hi @digitaljunk,
look for this file:  /OctoPrint/data/filamentmanager/filament.db.
BR
Olli

**Comment by digitaljunk** [comment]
> Hi @digitaljunk,
> look for this file: /OctoPrint/data/filamentmanager/filament.db.
> BR
> Olli
Hi @OllisGit,
Just perfect. Saved me a lot of time. Thank you! 
BR Rob
