### ISSUE TITLE
Add notes to Spool

### ISSUE THREAD

**Issue by JcMinarro** [OllisGit/OctoPrint-FilamentManager#12]
**Describe the solution you'd like**
When I configure a new spool, I would like to add some notes to it.
Would be great to have an input box where we can write some text.
Some example could see store info about the ideal temperature or any other information we want to store related with the filament

**Describe alternatives you've considered**
Add an extra input box on the Spool Popup that allow us insert some notes

**Comment by OllisGit** [comment]
Please take a look to my other plugin: https://github.com/OllisGit/OctoPrint-SpoolManager
There you can add notes to each spool.

**Comment by JcMinarro** [comment]
Hello  @OllisGit 
Are they complementary? 
I mean, I have already configured all my Spools on the previous plugin, if I install this new one, would I get the information from the other plugin?
Will they be updated simultaneously?

**Comment by OllisGit** [comment]
Hi @JcMinarro,

you can install both plugins in parallel. Each plugin use it's own database. There is no synching between the two plugins.

If you install SpoolManager you can export the old database from FilamentManager as a CSV, cleanup or add more informations (like notes) and import the CSV in the SpoolManager-Database.

PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.
