### ISSUE TITLE
2-spool empty warning

### ISSUE THREAD

**Issue by erichiller** [OllisGit/OctoPrint-FilamentManager#13]
My printer has dual extruders & filament spools. If one filament is empty, I get a notice about not enough filament, even when I'm not using that spool.

**Steps to reproduce**
1. With a two spool printer have one spool set to 0 remaining
2. Print something
3. Observe notice in top right
> Insufficient filament
> The current print job needs more material than what's left on the selected spool.

**Expected behavior**
Only error when using the spool that is empty.

**Notice**
![Screenshot_20201021-093515_Chrome](https://user-images.githubusercontent.com/5379325/96743149-ea258080-1380-11eb-9d3d-c4497b08ca8a.jpg)

**Selected Spools**
![Screenshot_20201021-093534_Chrome](https://user-images.githubusercontent.com/5379325/96743247-03c6c800-1381-11eb-825a-ad5922bddcf8.jpg)

**First Spool & spool in use**
![Screenshot_20201021-093538_Chrome](https://user-images.githubusercontent.com/5379325/96743314-180ac500-1381-11eb-9681-86982cdbe350.jpg)

**Second spool (empty)**
![Screenshot_20201021-093529_Chrome](https://user-images.githubusercontent.com/5379325/96743369-29ec6800-1381-11eb-9082-854e8337c245.jpg)

## Update
To add to the above, I now realize ( after using the 2nd spool ) that the counters on the second spool do not decrement at all. I'm not sure if this should be a separate issue?

**Comment by OllisGit** [comment]
Hi @erichiller,

because I don't have a dual extruder printer, please provide your gcode so that I can try to reproduce the behaviour with a "virtual printer".

PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.

**Comment by OllisGit** [comment]
no feedback -> closed
