### ISSUE TITLE
Predefined material pulldown with density

### ISSUE THREAD

**Issue by MaikelKelder** [OllisGit/OctoPrint-FilamentManager#18]
Just an addition to ease of use, since most of us dont know the density of their filament, since most fabricants dont tell them.

Using this list will geive a good template per material, and still give the option to change.
https://bitfab.io/blog/3d-printing-materials-densities/

![image](https://user-images.githubusercontent.com/37801691/98483747-38ed6a00-220b-11eb-9273-0c3bdd6c1895.png)

**Comment by OllisGit** [comment]
fyi: It is now in the Wiki: https://github.com/OllisGit/OctoPrint-FilamentManager/wiki
