### ISSUE TITLE
Spool selection when print starts

### ISSUE THREAD

**Issue by taker218** [OllisGit/OctoPrint-FilamentManager#21]
**Describe the bug**
I select the currently loaded spool in the widget and when I start the print, the dialogue comes up to confirm the selection. I would have thought that the currently selected spool would be the standard one in the dialogue. But I have to select this spool everytime I start a print again and can't just confirm the dialogue.

**Steps to reproduce**

**Expected behavior**

**Did the same happen when all other 3rd party plugins are disabled?**
If not which plugin is causing the issue?

**Log file**
Drag and drop the octoprint.log here.

**Screenshots**
<img width="270" alt="2020-11-24 13_39_47-CR10  OctoPrint" src="https://user-images.githubusercontent.com/15029277/100095376-ab408a00-2e5a-11eb-9cb1-b2228b42d4b8.png">
<img width="425" alt="2020-11-24 13_39_55-CR10  OctoPrint" src="https://user-images.githubusercontent.com/15029277/100095377-ab408a00-2e5a-11eb-9001-0854956b451a.png">

**Additional context**

**Comment by Ajimaru** [comment]
Hello @taker218 , what you discribe is not a bug, see #8 
![grafik](https://user-images.githubusercontent.com/38381946/100192112-9bc05000-2ef1-11eb-8873-12607d5ee86d.png)

**Comment by taker218** [comment]
I think the issue in #8 is different, since it's about changing the spool in the selection before the print.

The dialogue before the print should have the spool, which is selected in the widget, as default selection.
At least that's what I was expecting as a default behaviour.

**Comment by Ajimaru** [comment]
If the dialogue behaves how you describe then the dialogue is redundant. As you know user unintentionally not read message boxes.
It make sense that the user actively have to choose the correct filament again in this conformation dialogue.
