### ISSUE TITLE
Colors picker and informative color icon

### ISSUE THREAD

**Issue by mclei-asw** [OllisGit/OctoPrint-FilamentManager#25]
It would be great to add a color picker to filament details dialog and then display a colored square in the combobox on main form. Something like in Prusa Slic3r.

I am using this plugin mainly to inform other users about the colors and materials currently loaded in MMU. It will help to directly see the colors.

**Comment by OllisGit** [comment]
Hi @mclei-asw,

the color-picker feature is implemented in https://github.com/OllisGit/OctoPrint-SpoolManager plugin.

So, if you need the color picker, please switch to the spoolmanager. I will not implement such feature in the FilamentManager.
