### ISSUE TITLE
Prusaslicer Beta 2.3.0 'No filament from Meta'

### ISSUE THREAD

**Issue by rickyh777** [OllisGit/OctoPrint-FilamentManager#29]
When slicing something with prusaslicer Beta 2.3.0, the filament meta data must have moved as filament Manager no longer detects it. It can therefore no longer determine usage and I get the 'No filament detected from meta' error. I did slice with the fully released prusaslicer version and filament manager worked fine, it has something to do with the beta. Hoping you guys might be able to get out in front of it before the full release and a lot of people start having issues!

Thanks so much for all the development work on this I absolutely love filament manager!

**Comment by OllisGit** [comment]
Hi @rickyh777,

sorry to say, but I have no idea what you mean with "No filament detected from meta". I am not the original author of this plugin and in the sourcecode I couldn't find such error message.

Please provide a screenshot and the gcode file, so that I am able to reproduce the issue.

**Comment by OllisGit** [comment]
no feedback -> closed

**Comment by git-zombie** [comment]
I'm slicing from Cura and got the same issue. 

![image](https://user-images.githubusercontent.com/17103101/120115584-57d52e80-c152-11eb-8252-24fda3f81fa3.png)

**Comment by OllisGit** [comment]
@git-zombie ticket is closed and related to plugin [CostEstimation-Plugin](https://github.com/OllisGit/OctoPrint-CostEstimation). Solution, see readme (startpage)
