### ISSUE TITLE
No filament substracted on power outrage

### ISSUE THREAD

**Issue by drgoku282** [OllisGit/OctoPrint-FilamentManager#3]
**Describe the bug**
I've noticed that the filament usage is not being tracked constantly by the software. Yesterday I had a power outrage two hours in in a 7ish hour long print, and the filament usage was not updated after power was back and I restarted the printer.

**Steps to reproduce** (I don't think is a good idea to reproduce this, lol)
1. Register remaining filament in the spool.
2. Start the print as normal and let it work for a while.
3. Cut the power to the printer.
4. Restart the printer and check the amount of filament spool again.

**Expected behavior**
I was expecting to track the used filament until the moment the power failed, instead I the spool had the same amount of material that it had before starting the print.

**Did the same happen when all other 3rd party plugins are disabled?**
Didn't test while disabling other plugins.

**Log file**
Here it is, I don't think if it can help since it can't log anything if the rpi don't have power.
[octoprint.log](https://github.com/OllisGit/OctoPrint-FilamentManager/files/5249001/octoprint.log)

**Additional context**
I don't know if this is a octoprint limitation but maybe active tracking can solve this issue, maybe save usage after each layer change or in a time/progress basis.

**Comment by OllisGit** [comment]
Currently the usage is only stored after a print and not constantly.
Maybe I find a solution for this.
