### ISSUE TITLE
Hide empty Spools in Sidebar

### ISSUE THREAD

**Issue by realbadfox** [OllisGit/OctoPrint-FilamentManager#34]
Hallo,

really great Plugin, but is it possible to hide empty Spools in the Sidebar in Octoprint, so that the list won't be so long?
You can make a checkbox in the settings of the Plugin to enable or disable that feature.

yours Chris

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by OllisGit** [comment]
Hi,

this request is duplicated, see #6!
PS. it is already implemented, see https://github.com/OllisGit/OctoPrint-SpoolManager/issues/81

**Comment by realbadfox** [comment]
But i would love to have it in the filament manager not spool manager
