### ISSUE TITLE
FilamentManager 1.7.1 and Print Job History

### ISSUE THREAD

**Issue by rmilyard** [OllisGit/OctoPrint-FilamentManager#37]
**Describe the bug**
Since updating to this version I keep getting this when start OctoPrint.

Optional plugins
To get the real power of the Print Job History - Plugin you need the following plugins installed/enabled:

FilamentManager (missing)
 disable optional plugin check Close

**Steps to reproduce**

**Expected behavior**

**Did the same happen when all other 3rd party plugins are disabled?**
If not which plugin is causing the issue?

**Log file**
Drag and drop the octoprint.log here.

**Screenshots**

**Additional context**

**Comment by moong8te** [comment]
Issue also reported here with more details from different users:
https://github.com/OllisGit/OctoPrint-FilamentManager/issues/38
