### ISSUE TITLE
API call support

### ISSUE THREAD

**Issue by phajduk** [OllisGit/OctoPrint-FilamentManager#39]
I believe it would be useful to set current spool using API call. When OctoPrint is used by external tools like mobile apps or some automation scripts job is sent to OctoPrint via API, and last set spool is used. 

It would be nice to set some desired spool before programmatic job execution.

**Comment by OllisGit** [comment]
This was one of the feature I include in one of the last releases.
See MR https://github.com/OllisGit/OctoPrint-FilamentManager/pull/28

BUT...I need to document it in the readme, because it was slightly changed in the final release...give me some time and I will come back to you

**Comment by OllisGit** [comment]
small hint in readme added.
