### ISSUE TITLE
Hide Empty spools shows spools that is more than 100% used (inactive spools)

### ISSUE THREAD

**Issue by realbadfox** [OllisGit/OctoPrint-FilamentManager#41]
Hallo,

is it possible to hide empty spools shows spools that is more than 100% used (inactive spools)?
Would be really great if the Filament Manager can do this same like SpoolManager

Could it be possible to manually mark a spool as empty, instead of correcting the usage amount?

yours chris

**Comment by cmoe71** [comment]
I would like to have that implemented too as I don't like to delete empty spools for history reasons!
(Thanks for maintaining this plugin)

**Comment by OllisGit** [comment]
@realbadfox please delete the PullRequest in the old Git-Hub repository....or did you already implement this feature.
https://github.com/malnvenshorn/OctoPrint-FilamentManager/pull/234
Thx, in advance
Olli

**Comment by OllisGit** [comment]
Hi,
something like that:
![image](https://user-images.githubusercontent.com/24205767/115442998-fa74c600-a212-11eb-81f6-338fe4d031e4.png)

**Comment by cmoe71** [comment]
Would be o.k. for me, best regards, Clemens

**Comment by OllisGit** [comment]
Hi @realbadfox, @cmoe71,
latest version 1.8.0 include this feature.
Please test and give feedback.

Thx, in advance
Olli

**Comment by cmoe71** [comment]
Hi Olli,

played around with it - works fine for me, thanks for your efforts!

Best regards,
Clemens
