### ISSUE TITLE
Change Spool during print

### ISSUE THREAD

**Issue by EagleEyeBW** [OllisGit/OctoPrint-FilamentManager#42]
I start my prints directly from Slic3er, so I have no option to confirm that I whant to use a specific spool. But sometimes I forgot to change the current spool.
So is it possible to provide the option to change the spool during the print?

**Comment by EagleEyeBW** [comment]
ups wrong repo :D

**Comment by OllisGit** [comment]
Nope, you need to cancel the print and start again, sorry!
