### ISSUE TITLE
Request of some functions

### ISSUE THREAD

**Issue by FlexerJR** [OllisGit/OctoPrint-FilamentManager#43]
Hello OllisGit,

thanks for maintaining this plugin. I have some improvements for this one. The biggest thing is, that the way to the plugin for the user is horrible. I have to click on settings and then i have to scroll down to the endless list of plugins to find Filament Manager. 

It would be awesome to have one button to pop up the Filament Manager just with ONE click. It is so annoying. Sorry but somebody had to sayit.

Some more improvments:
-Please make it possible to change spools during the print. I'm changing spool due to different print colors. 
-Make it possible to edit all passive spools during the print. (Not for the active spool during printing)
-I use Spoolmanager as well. There are a lot more options to select. Just take a look at the image 

![image](https://user-images.githubusercontent.com/40354380/106624795-52861f80-6576-11eb-9ddd-998937275d6b.png)

Best regards

**Comment by locki-cz** [comment]
+ add some picture ... spool or colour

**Comment by OllisGit** [comment]
Hi @FlexerJR,

your first point was the reason why I started with SpoolManager ;-) 

Changing Spools is currently not supported in SpoolManager as well, but it is on the roadmap.

@locki-cz these two feature are already implemented in SpoolManager-Plugin.
