### ISSUE TITLE
FilamentManager not displaying Filament Tool data

### ISSUE THREAD

**Issue by ynygma** [OllisGit/OctoPrint-FilamentManager#45]
I installed FilamentManger, delete my cache, etc and I can add the Spool, etc and that shows up at the bottom left panel with a dropdown menu but on the top right, I am not seeing any data about how much Filament is left, etc. as it shows in the screenshots.

Is there something else I need to enable?

**Steps to reproduce**
No steps to reproduce as it is just not displaying any data

**Expected behavior**
To see the Filament used data that should be displayed underneath the Timelapse line in the left panel of OctoPrint

**Did the same happen when all other 3rd party plugins are disabled?**
No

**Log file**
Drag and drop the octoprint.log here.
[octoprint.log](https://github.com/OllisGit/OctoPrint-FilamentManager/files/6008435/octoprint.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/58670548/108474198-aa9a7280-7254-11eb-877c-803ad4b0c0bd.png)

**Additional context**
none that I can think of:)

**Comment by StephanBeutel** [comment]
I'm also missing some data in the side bar. 
Filament length and weight is displayed, but the costs are not displayed.
