### ISSUE TITLE
Nozzle heat too high

### ISSUE THREAD

**Issue by BenDavidson90** [OllisGit/OctoPrint-FilamentManager#50]
Hi,

Since some days, I noticed thant my printer heat the nozzle 60° higher than what was set in Cura.
I tested first by printing my files directly on the printer and all is OK so the problem is relative to octoprint.
I came across [this issue](https://github.com/malnvenshorn/OctoPrint-FilamentManager/issues/235) on the source repo that is the same as me.
So, I disabled Filament Manager, tested the same files as before and  the problem disappear, so I concluded that the problem is finaly comming from the Filament Manager plugin.

Is the problem known ?

**Comment by OllisGit** [comment]
Hi @BenDavidson90,
not known!

Did you already checked your spool configuration in FilamentManager plugin?

In this example the selected spool has on offset of ```-20``` and in gcode ```M104 S200```. The result after print was started looks like this:

![image](https://user-images.githubusercontent.com/24205767/115306788-98f81d00-a168-11eb-891a-201687741d9f.png)

**Comment by BenDavidson90** [comment]
Hi,
I did few tests today and it turns out that it was my fault: I had set the temperature offset of the spool at 200...
I use SpoolManager too and as in this one you can adjust the filament temperature I must have confused the two. Sorry !
