### ISSUE TITLE
Lock the currently selected spool for all other printers accessing the same database

### ISSUE THREAD

**Issue by cmoe71** [OllisGit/OctoPrint-FilamentManager#52]
As I use an external database for my filaments I would like to lock a spool (Spool Nr. 7) which is at the moment in use on another printer. Working and preparing another printer it is not possible to select Spool Nr. 7 because it is already in use on the other printer (Same spool can't be on two printers the same time.).
Best regards, Clemens

**Comment by OllisGit** [comment]
hi @cmoe71,

it is a nice idea and I will put this feature on on long-term SpoolManager-Backlog (https://github.com/OllisGit/OctoPrint-SpoolManager/projects/1#card-59393636)

But first, I need to finalize the external database feature.
