### ISSUE TITLE
When dialogue pops up confirming spool - no spool selected

### ISSUE THREAD

**Issue by tonnic** [OllisGit/OctoPrint-FilamentManager#54]
Not sure if this is a bug or designed this way, but when you hit print with a spool selected and have the dialogue turned on, the popup doesn't have the current spool selected, but you have to manually select the right spool.  Doesn't seem like a confirmation box, but more of a selection box.

**Comment by OllisGit** [comment]
Well this behaviour was one of the reason why I started developing the SpoolManager-Plugin.

By design, it is a confirmation dialog, see https://github.com/malnvenshorn/OctoPrint-FilamentManager/issues/85
