### ISSUE TITLE
Upgrade to support Python 3.4.9

### ISSUE THREAD

**Issue by jmlg10** [OllisGit/OctoPrint-FilamentManager#56]
running Octoprint on a Windows PC running python 3.9.4, could it be possible to have an update of this plug-in?

Many Thanks

**Comment by jmlg10** [comment]
![image](https://user-images.githubusercontent.com/33903686/114432749-4f845c80-9bc1-11eb-823a-664ea2751e4a.png)

**Comment by OllisGit** [comment]
Hi @jmlg10,

please provide the full octoprint.log. I need to identify which function is not working. Maybe it has nothing to do with python 3.9.4.

**Comment by jmlg10** [comment]
Hi Ollis,

Here is the Log

Let me know if you find something I can resolve.

Many Thanks

Cordialement / Best Regards

Jean-Michel LE GOFF | Responsable Recherches Numériques | Louis Vuitton Malletier | 2, Rue du Pont-Neuf, 75001 Paris, France | Phone: +33 155803048 | Mobile : +33 664405492 | Email address:  ***@***.***

De : OllisGit ***@***.***>
Envoyé : mardi 13 avril 2021 23:41
À : OllisGit/OctoPrint-FilamentManager ***@***.***>
Cc : Jean-Michel LE GOFF ***@***.***>; Mention ***@***.***>
Objet : Re: [OllisGit/OctoPrint-FilamentManager] Upgrade to support Python 3.4.9 (#56)

________________________________
WARNING: This is an external email. Shall you have any doubt, report any suspicious e-mail by clicking on the "Report suspicious e-mail" button in Outlook.
________________________________


Hi @jmlg10<https://urldefense.com/v3/__https:/github.com/jmlg10__;!!Lt0KOR8!E0CWFv2qGspQy8iRZWjZZbNPelzj0eOPcOwAciSqrBlup8a6QlsF7CfQme5Ra9Tpzi4VMZusteXExg$>,

please provide the full octoprint.log. I need to identify which function is not working. Maybe it has nothing to do with python 3.9.4.

**Comment by jmlg10** [comment]
[octoprint.log](https://github.com/OllisGit/OctoPrint-FilamentManager/files/6309473/octoprint.log)
Hello,
Here is the log.
let me know if you find something I can resolve.
Many Thanks

**Comment by OllisGit** [comment]
Hi @jmlg10,
found this in your logfile: 
```
AttributeError: module 'time' has no attribute 'clock'
```
duplicated issue, see #23 ...short python version downgrade....or wait for a fix
