### ISSUE TITLE
Color selection for spools

### ISSUE THREAD

**Issue by ingo916** [OllisGit/OctoPrint-FilamentManager#57]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice to have a color picker and assign the corresponding color to the spool I have entered. also add a column header Color
**Describe alternatives you've considered**
None

**Additional context**

![image](https://user-images.githubusercontent.com/41309095/114933538-a1112f00-9ded-11eb-8600-67c175987dc8.png)

![image](https://user-images.githubusercontent.com/41309095/114933822-fcdbb800-9ded-11eb-8b31-5ec389633901.png)

**Comment by OllisGit** [comment]
This feature is implemented in SpoolManager and will not implemented in FM, sorry!

**Comment by ingo916** [comment]
SpoolManager currently does not support shared database. That’s why I switched to FilamentManager.
