### ISSUE TITLE
Add support to change the currency from € to £ or $

### ISSUE THREAD

**Issue by TheTechGiant610** [OllisGit/OctoPrint-FilamentManager#58]
**Is your feature request related to a problem? Please describe.**
I would like to be able to change the currency of the filament costs from € to either £ or $ please?

**Describe the solution you'd like**
A drop down to select a currency value or white space to enter one.

**Describe alternatives you've considered**
I don't see an alternative

**Additional context**
None

**Comment by OllisGit** [comment]
Already there:
![image](https://user-images.githubusercontent.com/24205767/115301687-d4dbb400-a161-11eb-8666-f4a72ba0cd04.png)
![image](https://user-images.githubusercontent.com/24205767/115301726-e3c26680-a161-11eb-9e30-b2215e1c3e05.png)
