### ISSUE TITLE
Hide spools

### ISSUE THREAD

**Issue by poutnik** [OllisGit/OctoPrint-FilamentManager#6]
Hello, thanks for this great plugin.
I'd like to request a feature to allow me to hide a spool from the list on the sidebar, yet not to delete the spool entirely from the database - I have some filaments that I really like, I buy them repeatedly, but I sometimes don't have them - would be great if I could hide them, yet keep the (best) settings I already have found...

Thanks for consideration

Jiri

**Comment by jeremyhaynes217** [comment]
I came here to ask for basically the same thing. I'd like an option to turn off any spools that are at 0 remaining. I need to keep them in the database so my Grafana dashboard can use it to calculate the cost of old prints, but I don't need to see them in the drop down in the sidebar or in the pop up.

**Comment by elpeter25** [comment]
I arrived here looking for the same feature. It would be great to be able to hide spools from drop-down list either manually selecting them in settings or automatically when they reach 0.

Thanks and keep up the good work!

**Comment by elpeter25** [comment]
Hi,
Still no news for this suggestion? It would we awesome to be able to hide empty spools from the list.

Cheers!

**Comment by Ajimaru** [comment]
Would be a handy feature.

**Comment by OllisGit** [comment]
Hi,

this feature is planed for the SpoolManager-Plugin, see https://github.com/OllisGit/OctoPrint-SpoolManager/issues/81

PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.
