### ISSUE TITLE
Can't get through dialogue box the first time after connecting to octoprint UI

### ISSUE THREAD

**Issue by emilyboda** [OllisGit/OctoPrint-FilamentManager#60]
**Describe the bug**
The first time I print after the octoprint UI has been reloaded, the dialogue box won't let me click start print after selecting a filament roll. The box stays greyed out and won't click. I have to exit the dialogue box, and start the print a second time, and then it will allow me to hit the start print button.

**Steps to reproduce**
1. Make sure the "dialogue box to confirm filament" option is on in the plugin settings
2. reload the octoprint UI
2. Click the print icon on one of your files
3. select the same filament roll you have selected in the filament manager
3. try to click the start print button, it won't let you.
4. exit out of the dialogue box
5. click the print icon on the file again
6. now you can continue through the dialogue box

**Comment by OllisGit** [comment]
Hi @emilyboda,
I was not able to reproduce the issue. The print-button is enabled after I select the currently selected spool.

Is this behaviour in all Browsers the same? 
Did you try to clear the browser cache?
