### ISSUE TITLE
I can't get through the dialogue box if I've selected a filament roll that's different than the one that is selected in the manager on the main page

### ISSUE THREAD

**Issue by emilyboda** [OllisGit/OctoPrint-FilamentManager#61]
**Describe the bug**
When I start a print, the dialogue box opens to ask me to confirm which filament roll I'm using. If I change which filament roll I'm using at this point with the dialogue box to one other than the one that is selected in the manager on the main page, the start print button is greyed out and I can't click to start the print.

**Steps to reproduce**
1. make sure the "confirm selected filament roll with a dialogue box" option is on in the plugin settings
2. click the print icon on one of your files
3. change the selected filament roll to one other than the one that is selected on the manager on the main page
4. try to start your print, you can't

**Comment by OllisGit** [comment]
Well, this works as designed! The confirm-dialog is a "double safty-net" and not a "reselecting-dialog".
