### ISSUE TITLE
Ability to change Currency

### ISSUE THREAD

**Issue by Kentilsha13** [OllisGit/OctoPrint-FilamentManager#65]
**Is your feature request related to a problem? Please describe.**
Would it be possible to add the ability to change the currency?  Possibly to $ for the US.  

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Rebel154** [comment]
Open the settings page for filament manager and click the small spanner icon at the top right. Select the 'Appearance' tab and put in your preferred currency simple and click 'Save'.
