### ISSUE TITLE
Changing number of extruders permanently affects the number of filament manager tools

### ISSUE THREAD

**Issue by techfreek** [OllisGit/OctoPrint-FilamentManager#79]
**Describe the bug**
As part of testing an integration of this plugin into OctoScreen (https://github.com/Z-Bolt/OctoScreen/pull/315) I modified my OctoPrint settings to say I had 2 extruders to see what the UI looked like. I saw the results, was content, and changed OctoPrint back to 1 extruder. Ever since, I've seen that the "plugin/filamentmanager/selections" endpoint still returns 2 tools. This is even after rebooting and even upgrading to OctoPrint 1.7

**Steps to reproduce**
1. Open Settings
2. Click on Printer Profiles
3. Edit the active Profile
4. Click on Hotend & Extruder
5. Change to 2 extruders
6. Save
7. Check the output of "plugin/filamentmanager/selections"
2. Repeat steps 1-4
3. Change extruders to 1
4. Save
5. See that "plugin/filamentmanager/selections" still returns 2 tools

To check the output of the "plugin/filamentmanager/selections" endpoint, I used chrome dev tools to "Copy as cURL" and run that.

**Expected behavior**
"plugin/filamentmanager/selections" returns the correct number of tools

**Did the same happen when all other 3rd party plugins are disabled?**
Have not tested

**Log file**
No logs related to filament manager

**Screenshots**

**Additional context**

**Comment by OllisGit** [comment]
Hi @techfreek,
new version 1.9.0 now only response with the max tool count selection. 

Please test and give feedback
Olli
