### ISSUE TITLE
Android app?

### ISSUE THREAD

**Issue by WimVDK** [OllisGit/OctoPrint-FilamentManager#84]
So i just found this plugin as the android app i was using "RollingUp: Filament manager" supposedly had the ability to sync spools. I had nearly a dozen different colors in it and total about 2 dozen spools. Couple weeks ago i had to do a factory reset of my phone, logged back in with the google account and well, NONE of my spools synced back. Meaning i lost months of "work" with spool weights etc.

While i look for a possible replacement, i found this as a possible canditate. Not exactly what i was looking for but better than nothing right? Now to the point, do you happen to have a matching android app (even better one that would sync with the profiles added in this plugin)? I suppose this one accurately tracks expended filament, even on a print failure?

Thanks in advance, looking forward to tinkering with this little thing :)

**Comment by OllisGit** [comment]
Hi @WimVDK,

did you also check this plugin:  https://github.com/OllisGit/OctoPrint-SpoolManager
It has more feature (except two) and is under active development. 
Regarding to FM it has currently two drawbacks: no profile support and no external database. But you export/backup your data ;-)

Btw. I don't see any advantage of a native android app...maybe a better responsive web-site.

**Comment by WimVDK** [comment]
yeah you can close this one. It's me too in issue #212. I've moved to that one. I managed to import my spools to a degree (had to manually fix some stuff in names etc). I havent had the time to check it out in detail or respond to #212 i'll do that as soon as i can.
