### ISSUE TITLE
Not showing up anymore

### ISSUE THREAD

**Issue by michellauser** [OllisGit/OctoPrint-FilamentManager#86]
I have the Problem, after update OctoPrint to 1.7.2 Filament Manager is not shwoing up ind OctoPtrint anymore - tired deactivate - activte, uninstall, reinstall - nothing works anymore....

**Comment by OllisGit** [comment]
Please attach the octoprint.log file maybe there is an error message.

**Comment by michellauser** [comment]
Hi Olli - thanks for your reply - found the error yetserday. While updating OctoPrint and invorenment to latest versions i change the update channel to Maintenance RCs an forgot to set it back - this was the rerason why the filament manger didn't work anymore. By changing the settings back to release channel stable, i was able to reinstall filament manger and import backup. Everything is working fine now.

Best regards Michael
