### ISSUE TITLE
Cannot select spool for print.

### ISSUE THREAD

**Issue by grrminator** [OllisGit/OctoPrint-FilamentManager#87]
For the dropdown starting the print, the spool selection screen comes up, but if you select a spool, you cannot start the print, if you select the "Select spool" option, you can print.

Any way to fix this issue?

**Comment by OllisGit** [comment]
Hi @grrminator,
this is not a bug...it's a feature.

The dialog is a "confirmation" dialog, so you need to pick the same spool you selected in the sidebar to confirm that "you know what your are doing".

So, in your case you didn't select a spool for the print in the sidbar and then you need to select also the ```--- Select Spool ---``` enrty.
